build:
  environment:
    php:
      version: "7.4"
      compile_options: "--enable-gd --enable-cli --with-xsl --with-sodium --with-openssl --enable-bcmath --enable-mbstring --with-imap-ssl --enable-pcntl --with-zlib"
    node: "v12.9.1"
  project_setup:
    override:
      - yes | pecl install redis
      - php artisan passport:keys
  cache:
    directories:
      - vendor/
      - ~/.composer/cache/
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
  tests:
    before:
      - chmod -R 777 storage
      - chmod -R 777 bootstrap/cache
    override:
      - command: vendor/bin/phpunit --coverage-clover coverage.xml
        coverage:
          file: coverage.xml
          format: clover
