build:
  image: default-bionic
  environment:
    php:
      version: 7.4
      pecl_extensions:
        - zip
        - pcov
  nodes:
    automated-tests:
      services:
        mysql:
          image: "mysql:8"
          command: --default-authentication-plugin=mysql_native_password
          ports:
            - 3306
          env:
            MYSQL_DATABASE: test
            MYSQL_ALLOW_EMPTY_PASSWORD: true
            MYSQL_ROOT_PASSWORD: ''
      commands:
        - pwd
        - checkout-code ~/build
        - pwd
        - cd ~/build
        - pwd
        - yes | pecl install redis
        - php -v
        - export DB_USERNAME=root
        - chmod -R 777 storage
        - chmod -R 777 bootstrap/cache
        - php artisan passport:keys
        - php -dpcov.enabled=1 -dpcov.directory=. -dpcov.exclude="~vendor~" ./vendor/bin/phpunit --coverage-clover coverage.xml --stop-on-error --stop-on-failure
          coverage:
              file: coverage.xml
              format: clover
