build:
  environment:
    php:
      version: "7.4"
      compile_options: "--enable-gd --enable-cli --with-xsl --with-sodium --with-openssl --enable-bcmath --enable-mbstring --with-imap-ssl --enable-pcntl --with-zlib"
    node: "v12.9.1"
  project_setup:
    override:
      - yes | pecl install redis
      - php artisan passport:keys
  cache:
    directories:
      - vendor/
      - ~/.composer/cache/
  nodes:
    tests:
      environment:
        php:
          version: 7.4
          complie_options: '--enable-bcmath --without-pear --enable-mbstring'
          pecl_extensions:
            - zip
            - redis
    analysis:
      environment:
        php:
          version: 7.4
          pecl_extensions:
            - zip
            - redis
  tests:
    before:
      - chmod -R 777 storage
      - chmod -R 777 bootstrap/cache
    override:
      - command: vendor/bin/phpunit --coverage-clover coverage.xml
        coverage:
          file: coverage.xml
          format: clover
