build:
  environment:
    php:
      version: 7.4
      pecl_extensions:
        - zip
        - redis
        - pcov
  project_setup:
    override:
      - true
  cache:
    directories:
      - vendor/
      - ~/.composer/cache/
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

  tests:
    services:
        mysql: 5.7
    before:
      - sudo mysql -u root -e "CREATE DATABASE test"
      - export DB_USERNAME=scrutinizer
      - chmod -R 777 storage
      - chmod -R 777 bootstrap/cache
      - php artisan passport:keys
    override:
      - command: php -dpcov.enabled=1 -dpcov.directory=. -dpcov.exclude="~vendor~" ./vendor/bin/phpunit --coverage-clover coverage.xml --stop-on-error --stop-on-failure
        coverage:
          file: coverage.xml
          format: clover
