build:
  environment:
    node: "v12.9.1"
  project_setup:
    override:
      - php artisan passport:keys
  cache:
    directories:
      - vendor/
      - ~/.composer/cache/
  nodes:
    tests:
      environment:
        php:
          version: 7.4
          compile_options: '--enable-bcmath --without-pear --enable-mbstring'
          pecl_extensions:
            - zip
            - redis
    analysis:
      environment:
        php:
          version: 7.4
          pecl_extensions:
            - zip
            - redis
  tests:
    before:
      - chmod -R 777 storage
      - chmod -R 777 bootstrap/cache
    override:
      - command: vendor/bin/phpunit --coverage-clover coverage.xml
        coverage:
          file: coverage.xml
          format: clover
