build:
  environment:
    php: "7.4"
    node: "v12.9.1"
  dependencies:
    before:
      - sudo apt install php-gd
  cache:
    directories:
      - vendor/
      - ~/.composer/cache/
  tests:
    before:
      - chmod -R 777 storage
      - chmod -R 777 bootstrap/cache
    override:
      - command: vendor/bin/phpunit --coverage-clover coverage.xml
        coverage:
          file: coverage.xml
          format: clover
