build:
  environment:
    php:
      version: 7.4
      compile_options: "--enable-cli --with-openssl --with-imap-ssl --enable-bcmath --enable-mbstring --with-zlib --with-curl --enable-pcntl --enable-gd --with-xsl --with-sodium --with-zlib --without-pear"
      pecl_extensions:
        - zip
        - redis
        - pcov
  project_setup:
    override:
      - true
  cache:
    directories:
      - vendor/
      - ~/.composer/cache/
  nodes:
    tests-and-coverage:
      services:
        mysql: 5.7
    analysis:
      tests:
        override:
          - php-scrutinizer-run

  tests:
    before:
      - sudo mysql -u root -e "CREATE DATABASE test"
      - export DB_USERNAME=scrutinizer
      - chmod -R 777 storage
      - chmod -R 777 bootstrap/cache
      - php artisan passport:keys
    override:
      - command: php -dpcov.enabled=1 -dpcov.directory=. -dpcov.exclude="~vendor~" ./vendor/bin/phpunit --coverage-clover coverage.xml
        coverage:
          file: coverage.xml
          format: clover
