language: php

matrix:
  fast_finish: true

php:
  - 7.4

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer install
  - php artisan passport:keys

script:
  - php vendor/bin/phpunit --stop-on-error --stop-on-failure --coverage-clover coverage.xml

after_success:
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - ./codecov -t ${CODECOV_TOKEN}
