language: php

matrix:
  fast_finish: true

php:
  - 7.4

services:
  - mysql: 5.7

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - pecl install pcov
  - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS forge;'

install:
  - composer install
  - php artisan passport:keys

script:
  - export DB_DATABASE=forge
  - export DB_USERNAME=root
  - php -d pcov.enabled=1 -d pcov.directory=packages/ -d pcov.exclude=/Test\.php/ vendor/bin/phpunit --stop-on-error --stop-on-failure --coverage-clover coverage.xml

after_success:
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - ./codecov -t ${CODECOV_TOKEN}
