language: php

matrix:
  fast_finish: true

php:
  - 7.2
  - 7.3

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer install
  - php artisan passport:keys

script:
  - php vendor/bin/codecept run