language: php

matrix:
  fast_finish: true

php:
  - 7.4

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - pecl install pcov

install:
  - composer install
  - php artisan passport:keys

script:
  - php -d pcov.enabled=1 vendor/bin/phpunit --stop-on-error --stop-on-failure --coverage-clover coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
