language: php

matrix:
  fast_finish: true

php:
  - 7.4

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - printf "\n" | pecl install redis
  - composer install
  - php artisan passport:keys

script:
  - php vendor/bin/phpunit --stop-on-error --stop-on-failure --coverage-clover coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
