language: php

matrix:
  fast_finish: true

php:
  - 7.3

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer install
  - php artisan passport:keys

script:
  - php vendor/bin/codecept run --coverage-xml --fail-fast

after_success:
    - bash <(curl -s https://codecov.io/bash)