ignore:
  - "app"
  - "database"
  - "config"
  - "tests"
  - "packages/llstarscreamll/**/tests"
  - "packages/llstarscreamll/**/config"
  - "packages/llstarscreamll/**/database"
  - "packages/llstarscreamll/**/src/Facades"
  - "packages/llstarscreamll/**/src/Seeds"
  - "packages/llstarscreamll/**/src/*ServiceProvider.php"
